### ISSUE TITLE
[FEATURE] Web3 Form Wizard Integration ThirdWeb

### ISSUE THREAD

**Issue by gianksp** [webstudioso/wsm-form#1]
# Context

Interacting with a smart contract should be straightforward and easy. This task allows a builder to create an automatic form from a wizard by selecting a pre-built configuration from ThirdWeb Smart Contracts

# Tasks
- [ ] Web3 form wizard
- [ ] ThirdWeb options button
- [ ] ThirdWeb smart contract options with their descriptions

# Acceptance Criteria
- [ ] As a builder I can create a form from pre-built configuration from ThirdWeb smart contracts and at the same time link to launch on their dashboard
