### ISSUE TITLE
[FEATURE] Web3 Form Wizard Integration Cookbook

### ISSUE THREAD

**Issue by gianksp** [webstudioso/wsm-form#2]
# Context

Interacting with a smart contract should be straightforward and easy. This task allows a builder to create an automatic form from a wizard by selecting a pre-built configuration from Cookbook Smart Contracts

# Tasks
- [ ] Web3 form wizard
- [ ] CookBook options button
- [ ] CookBook smart contract options with their descriptions

# Acceptance Criteria
- [ ] As a builder I can create a form from pre-built configuration from CookBook smart contracts and at the same time link or tutorial to launch manually using Remix
