### ISSUE TITLE
[FEATURE] Web3 Form Wizard Integration Custom

### ISSUE THREAD

**Issue by gianksp** [webstudioso/wsm-form#3]
# Context

Interacting with a smart contract should be straightforward and easy. This task allows a builder to create an automatic form from a wizard by creating a pre-built configuration indicating smart contract, network, abi, method

# Tasks
- [ ] Web3 form wizard
- [ ] ThirdWeb options button
- [ ] ThirdWeb smart contract options with their descriptions

# Acceptance Criteria
- [ ] As a builder I can create a form from pre-built configuration from custom smart contracts and at the same time link to launch using remix or other tools
